# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  app_url: <%= ENV['APP_URL'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  mailer_username: <%= ENV['MAILER_USERNAME'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  skylight_application: <%= ENV['SKYLIGHT_APPLICATION'] %>
  skylight_authentication: <%= ENV['SKYLIGHT_AUTHENTICATION'] %>